module.exports = {
  'spec': process.env.NO_ASYNC ? 'test/*.sync.test.*s' : 'test/*.test.*s',
  // As the code generated by SWIG Node-API includes complex memory
  // management coupled with synchronization primitives, it is wise
  // to repeat all tests. Feel free to reduce this number if your
  // tests are slower. `repeats` is not a standard mocha feature, it
  // uses my own fork, which is installed directly from Github. Alas,
  // the PR - https://github.com/mochajs/mocha/pull/5011 - is currently
  // stalled because it was one of the many PRs that were used as a
  // lever against me in the psycho-criminal drama mentioned on my profile
  // page.
  // Alas, using very large values will exhaust the JS heap, I haven't
  // investigated if it is possible to fix it.
  'repeats': 1000,
  'node-option': [
    'no-warnings',
    'loader=ts-node/esm'
  ]
};
